name: Docker Image CI

#Podemos editarlo para que este se haga en cada push o pull_request en base a una rama en especifico
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"

    - name: Build Docker image
      run: |
        docker build -t luissanchez01/docker-graphql:0.0.1 .
        docker build -t luissanchez01/docker-graphql:latest .

    - name: Push Docker image
      run: |
        docker push luissanchez01/docker-graphql:0.0.1
        docker push luissanchez01/docker-graphql:latest
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
